from typing import Any, AsyncIterator

import scrapy
from scrapy.http import JsonRequest, Response

from locations.dict_parser import DictParser
from locations.hours import OpeningHours


class MoneygramSpider(scrapy.Spider):
    name = "moneygram"
    item_attributes = {"brand": "MoneyGram", "brand_wikidata": "Q1944412"}

    async def start(self) -> AsyncIterator[Any]:
        for country in [
            "AE",
            "AF",
            "AG",
            "AI",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AW",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BL",
            "BM",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CF",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CN",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "EC",
            "EE",
            "EG",
            "ES",
            "ET",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GF",
            "GH",
            "GI",
            "GM",
            "GN",
            "GP",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KM",
            "KN",
            "KR",
            "KW",
            "KY",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MD",
            "ME",
            "MF",
            "MG",
            "MH",
            "MK",
            "ML",
            "MM",
            "MN",
            "MQ",
            "MR",
            "MS",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PR",
            "PS",
            "PT",
            "PY",
            "QA",
            "RE",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SD",
            "SE",
            "SG",
            "SL",
            "SM",
            "SN",
            "SR",
            "SS",
            "ST",
            "SV",
            "SX",
            "SZ",
            "TC",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VG",
            "VI",
            "VN",
            "VU",
            "WS",
            "XK",
            "YE",
            "YT",
            "ZA",
            "ZM",
            "ZW",
        ]:
            yield JsonRequest(
                url=f"https://www.moneygram.com/locations/api/locations/states?country={country}",
                cb_kwargs={"country": country},
            )

    def parse(self, response: Response, **kwargs: Any) -> Any:
        for state in response.json()["states"]:
            yield JsonRequest(
                url=f'https://www.moneygram.com/locations/api/locations/cities?country={kwargs["country"]}&state={state["code"]}',
                callback=self.parse_cities,
                cb_kwargs={"country": kwargs["country"]},
            )

    def parse_cities(self, response, **kwargs):
        for city in response.json()["cities"]:
            yield JsonRequest(
                url=f'https://www.moneygram.com/locations/api/locations?address={city["city"]}&country={kwargs["country"]}',
                callback=self.parse_details,
                cb_kwargs={"country": kwargs["country"]},
            )

    def parse_details(self, response, **kwargs):
        for location in response.json().get("locations"):
            location.update(location.pop("locationDetails"))
            item = DictParser.parse(location)
            item["branch"] = item.pop("name")
            item["ref"] = " - ".join([item["ref"], kwargs["country"]])
            try:
                oh = OpeningHours()
                for key, value in location.get("locationOperatingHours").items():
                    day = key.replace("Hours", "")
                    open_time, close_time = value.split(" - ")
                    oh.add_range(day=day, open_time=open_time, close_time=close_time, time_format="%I:%M %p")
                item["opening_hours"] = oh
            except:
                pass

            yield item
