import re
from typing import Any, AsyncIterator

from scrapy import Spider
from scrapy.http import JsonRequest, Response

from locations.categories import Categories, apply_category
from locations.dict_parser import DictParser
from locations.hours import DAYS, DAYS_WEEKDAY, OpeningHours

# Colombia has no comprehensive list of Olimpica store cities published
# anywhere on the site; the store finder's underlying VTEX Master Data
# API rejects any query that is not filtered by an exact "municipio"
# match, so all DANE municipalities are queried and the ones without a
# result are simply skipped.
MUNICIPIOS = [
    "Abejorral",
    "Abriaquí",
    "Acacías",
    "Acandí",
    "Acevedo",
    "Achí",
    "Agrado",
    "Agua de Dios",
    "Aguachica",
    "Aguada",
    "Aguadas",
    "Aguazul",
    "Agustín Codazzi",
    "Aipe",
    "Albania",
    "Albán",
    "Alcalá",
    "Aldana",
    "Alejandría",
    "Algarrobo",
    "Algeciras",
    "Almaguer",
    "Almeida",
    "Alpujarra",
    "Altamira",
    "Alto Baudó",
    "Altos del Rosario",
    "Alvarado",
    "Amagá",
    "Amalfi",
    "Ambalema",
    "Anapoima",
    "Ancuyá",
    "Andalucía",
    "Andes",
    "Angelópolis",
    "Angostura",
    "Anolaima",
    "Anorí",
    "Anserma",
    "Ansermanuevo",
    "Anzoátegui",
    "Anzá",
    "Apartadó",
    "Apulo",
    "Apía",
    "Aquitania",
    "Aracataca",
    "Aranzazu",
    "Aratoca",
    "Arauca",
    "Arauquita",
    "Arbeláez",
    "Arboleda",
    "Arboledas",
    "Arboletes",
    "Arcabuco",
    "Arenal",
    "Argelia",
    "Ariguaní",
    "Arjona",
    "Armenia",
    "Armero",
    "Arroyohondo",
    "Astrea",
    "Ataco",
    "Ayapel",
    "Bagadó",
    "Bahía Solano",
    "Bajo Baudó",
    "Balboa",
    "Baranoa",
    "Baraya",
    "Barbacoas",
    "Barbosa",
    "Barichara",
    "Barranca de Upía",
    "Barrancabermeja",
    "Barrancas",
    "Barranco de Loba",
    "Barranquilla",
    "Becerril",
    "Belalcázar",
    "Bello",
    "Belmira",
    "Beltrán",
    "Belén",
    "Belén de Umbría",
    "Belén de los Andaquíes",
    "Berbeo",
    "Betania",
    "Betulia",
    "Betéitiva",
    "Bituima",
    "Boavita",
    "Bochalema",
    "Bogotá",
    "Bojacá",
    "Bojayá",
    "Bolívar",
    "Bosconia",
    "Boyacá",
    "Brazuelo de Papayal",
    "Briceño",
    "Bucaramanga",
    "Bucarasica",
    "Buenaventura",
    "Buenavista",
    "Buenos Aires",
    "Buesaco",
    "Buga",
    "Bugalagrande",
    "Buriticá",
    "Busbanzá",
    "Cabrera",
    "Cabuyaro",
    "Cachipay",
    "Caicedo",
    "Caicedonia",
    "Caimito",
    "Cajamarca",
    "Cajibío",
    "Cajicá",
    "Calamar",
    "Calarcá",
    "Caldas",
    "Caldono",
    "Cali",
    "California",
    "Calima",
    "Caloto",
    "Campamento",
    "Campo de la Cruz",
    "Campoalegre",
    "Campohermoso",
    "Canalete",
    "Candelaria",
    "Cantagallo",
    "Cantón de San Pablo",
    "Caparrapí",
    "Capitanejo",
    "Caracolí",
    "Caramanta",
    "Carcasí",
    "Carepa",
    "Carmen de Apicalá",
    "Carmen de Carupa",
    "Carolina del Príncipe",
    "Cartagena de Indias",
    "Cartagena del Chairá",
    "Cartago",
    "Carurú",
    "Casabianca",
    "Castilla la Nueva",
    "Caucasia",
    "Cañasgordas",
    "Cepitá",
    "Cereté",
    "Cerinza",
    "Cerrito",
    "Cerro de San Antonio",
    "Chachagüí",
    "Chaguaní",
    "Chalán",
    "Chaparral",
    "Charalá",
    "Charta",
    "Chibolo",
    "Chigorodó",
    "Chima",
    "Chimichagua",
    "Chimá",
    "Chinavita",
    "Chinchiná",
    "Chinácota",
    "Chinú",
    "Chipaque",
    "Chipatá",
    "Chiquinquirá",
    "Chiriguaná",
    "Chiscas",
    "Chita",
    "Chitagá",
    "Chitaraque",
    "Chivatá",
    "Chivor",
    "Choachí",
    "Chocontá",
    "Chámeza",
    "Chía",
    "Chíquiza",
    "Cicuco",
    "Cimitarra",
    "Circasia",
    "Cisneros",
    "Ciudad Bolívar",
    "Ciénaga",
    "Ciénaga de Oro",
    "Ciénega",
    "Clemencia",
    "Cocorná",
    "Coello",
    "Cogua",
    "Colombia",
    "Colosó",
    "Colón",
    "Concepción",
    "Concordia",
    "Condoto",
    "Confines",
    "Consacá",
    "Contadero",
    "Contratación",
    "Convención",
    "Copacabana",
    "Coper",
    "Corinto",
    "Coromoro",
    "Corozal",
    "Corrales",
    "Cota",
    "Cotorra",
    "Covarachía",
    "Coveñas",
    "Coyaima",
    "Cravo Norte",
    "Cuaspud",
    "Cubarral",
    "Cubará",
    "Cucaita",
    "Cucunubá",
    "Cucutilla",
    "Cumaral",
    "Cumaribo",
    "Cumbal",
    "Cumbitara",
    "Cunday",
    "Curillo",
    "Curití",
    "Curumaní",
    "Cuítiva",
    "Cáceres",
    "Cáchira",
    "Cácota",
    "Cáqueza",
    "Cértegui",
    "Cómbita",
    "Córdoba",
    "Cúcuta",
    "Dabeiba",
    "Dagua",
    "Dibulla",
    "Distracción",
    "Dolores",
    "Donmatías",
    "Dosquebradas",
    "Duitama",
    "Duranía",
    "Ebéjico",
    "El Atrato",
    "El Bagre",
    "El Banco",
    "El Cairo",
    "El Calvario",
    "El Carmen",
    "El Carmen de Atrato",
    "El Carmen de Bolívar",
    "El Carmen de Chucurí",
    "El Carmen de Viboral",
    "El Carmen del Darién",
    "El Castillo",
    "El Cerrito",
    "El Charco",
    "El Cocuy",
    "El Colegio",
    "El Copey",
    "El Doncello",
    "El Dorado",
    "El Dovio",
    "El Espinal",
    "El Espino",
    "El Guacamayo",
    "El Guamo",
    "El Molino",
    "El Paso",
    "El Paujil",
    "El Peñol",
    "El Peñón",
    "El Pital",
    "El Piñón",
    "El Playón",
    "El Retiro",
    "El Retorno",
    "El Retén",
    "El Roble",
    "El Rosal",
    "El Rosario",
    "El Santuario",
    "El Socorro",
    "El Tablón",
    "El Tambo",
    "El Tarra",
    "El Zulia",
    "El Águila",
    "Elías",
    "Encino",
    "Enciso",
    "Entrerríos",
    "Envigado",
    "Facatativá",
    "Falán",
    "Filadelfia",
    "Filandia",
    "Firavitoba",
    "Flandes",
    "Florencia",
    "Floresta",
    "Florida",
    "Floridablanca",
    "Florián",
    "Fonseca",
    "Fortul",
    "Fosca",
    "Francisco Pizarro",
    "Fredonia",
    "Fresno",
    "Frontino",
    "Fuente de Oro",
    "Fundación",
    "Funes",
    "Funza",
    "Fusagasugá",
    "Fómeque",
    "Fúquene",
    "Gachalá",
    "Gachancipá",
    "Gachantivá",
    "Gachetá",
    "Galapa",
    "Galeras",
    "Galán",
    "Gama",
    "Gamarra",
    "Garagoa",
    "Garzón",
    "Gigante",
    "Ginebra",
    "Giraldo",
    "Girardot",
    "Girardota",
    "Girón",
    "González",
    "Gramalote",
    "Granada",
    "Guaca",
    "Guacamayas",
    "Guacarí",
    "Guachené",
    "Guachetá",
    "Guachucal",
    "Guadalupe",
    "Guaduas",
    "Guaitarilla",
    "Gualmatán",
    "Guamal",
    "Guamo",
    "Guapotá",
    "Guapí",
    "Guaranda",
    "Guarne",
    "Guasca",
    "Guatapé",
    "Guataquí",
    "Guatavita",
    "Guateque",
    "Guavatá",
    "Guayabal de Síquima",
    "Guayabetal",
    "Guayatá",
    "Gutiérrez",
    "Guática",
    "Gámbita",
    "Gámeza",
    "Génova",
    "Gómez Plata",
    "Güepsa",
    "Güicán",
    "Hacarí",
    "Hatillo de Loba",
    "Hato",
    "Hato Corozal",
    "Hatonuevo",
    "Heliconia",
    "Herrán",
    "Herveo",
    "Hispania",
    "Hobo",
    "Honda",
    "Ibagué",
    "Icononzo",
    "Iles",
    "Imués",
    "Inzá",
    "Inírida",
    "Ipiales",
    "Isnos",
    "Istmina",
    "Itagüí",
    "Ituango",
    "Iza",
    "Jambaló",
    "Jamundí",
    "Jardín",
    "Jenesano",
    "Jericó",
    "Jerusalén",
    "Jesús María",
    "Jordán",
    "Juan de Acosta",
    "Junín",
    "Juradó",
    "La Apartada",
    "La Argentina",
    "La Belleza",
    "La Calera",
    "La Capilla",
    "La Ceja",
    "La Celia",
    "La Cruz",
    "La Cumbre",
    "La Dorada",
    "La Esperanza",
    "La Estrella",
    "La Florida",
    "La Gloria (Cesar)",
    "La Jagua de Ibirico",
    "La Jagua del Pilar",
    "La Llanada",
    "La Macarena",
    "La Merced",
    "La Mesa",
    "La Montañita",
    "La Palma",
    "La Paz",
    "La Peña",
    "La Pintada",
    "La Plata",
    "La Playa de Belén",
    "La Primavera",
    "La Salina",
    "La Sierra",
    "La Tebaida",
    "La Tola",
    "La Unión",
    "La Uribe",
    "La Uvita",
    "La Vega",
    "La Victoria",
    "La Virginia",
    "Labateca",
    "Labranzagrande",
    "Landázuri",
    "Lebrija",
    "Leiva",
    "Lejanías",
    "Lenguazaque",
    "Leticia",
    "Liborina",
    "Linares",
    "Litoral de San Juan",
    "Lloró",
    "Lorica",
    "Los Andes",
    "Los Córdobas",
    "Los Palmitos",
    "Los Patios",
    "Los Santos",
    "Lourdes",
    "Luruaco",
    "Lérida",
    "Líbano",
    "López de Micay",
    "Macanal",
    "Macaravita",
    "Maceo",
    "Machetá",
    "Madrid",
    "Magangué",
    "Magüí Payán",
    "Mahates",
    "Maicao",
    "Majagual",
    "Malambo",
    "Mallama",
    "Manatí",
    "Manaure",
    "Manaure Balcón del Cesar",
    "Manizales",
    "Manta",
    "Manzanares",
    "Maní",
    "Mapiripán",
    "Margarita",
    "Marinilla",
    "Maripí",
    "Mariquita",
    "Marmato",
    "Marquetalia",
    "Marsella",
    "Marulanda",
    "María la Baja",
    "Matanza",
    "Medellín",
    "Medina",
    "Medio Atrato",
    "Medio Baudó",
    "Medio San Juan",
    "Melgar",
    "Mercaderes",
    "Mesetas",
    "Milán",
    "Miraflores",
    "Miranda",
    "Mistrató",
    "Mitú",
    "Mocoa",
    "Mogotes",
    "Molagavita",
    "Momil",
    "Mompós",
    "Mongua",
    "Monguí",
    "Moniquirá",
    "Montebello",
    "Montecristo",
    "Montelíbano",
    "Montenegro",
    "Monterrey",
    "Montería",
    "Morales",
    "Morelia",
    "Morroa",
    "Mosquera",
    "Motavita",
    "Moñitos",
    "Murillo",
    "Murindó",
    "Mutatá",
    "Mutiscua",
    "Muzo",
    "Málaga",
    "Nariño",
    "Natagaima",
    "Nechí",
    "Necoclí",
    "Neira",
    "Neiva",
    "Nemocón",
    "Nilo",
    "Nimaima",
    "Nobsa",
    "Nocaima",
    "Norcasia",
    "Norosí",
    "Nueva Granada",
    "Nuevo Colón",
    "Nunchía",
    "Nuquí",
    "Nátaga",
    "Nóvita",
    "Obando",
    "Ocamonte",
    "Ocaña",
    "Oiba",
    "Oicatá",
    "Olaya",
    "Olaya Herrera",
    "Onzaga",
    "Oporapa",
    "Orito",
    "Orocué",
    "Ortega",
    "Ospina",
    "Otanche",
    "Ovejas",
    "Pachavita",
    "Pacho",
    "Padilla",
    "Paicol",
    "Pailitas",
    "Paime",
    "Paipa",
    "Pajarito",
    "Palermo",
    "Palestina",
    "Palmar",
    "Palmar de Varela",
    "Palmas del Socorro",
    "Palmira",
    "Palocabildo",
    "Pamplona",
    "Pamplonita",
    "Pandi",
    "Panqueba",
    "Paratebueno",
    "Pasca",
    "Pasto",
    "Patía",
    "Pauna",
    "Paya",
    "Paz de Ariporo",
    "Paz del Río",
    "Pedraza",
    "Pelaya",
    "Pensilvania",
    "Peque",
    "Pereira",
    "Pesca",
    "Piamonte",
    "Piedecuesta",
    "Piedras",
    "Piendamó",
    "Pijao",
    "Pijiño del Carmen",
    "Pinchote",
    "Pinillos",
    "Piojó",
    "Pisba",
    "Pitalito",
    "Pivijay",
    "Planadas",
    "Planeta Rica",
    "Plato",
    "Policarpa",
    "Polonuevo",
    "Ponedera",
    "Popayán",
    "Pore",
    "Potosí",
    "Pradera",
    "Prado",
    "Providencia",
    "Providencia y Santa Catalina Islas",
    "Pueblo Bello",
    "Pueblo Nuevo",
    "Pueblo Rico",
    "Pueblo Viejo",
    "Pueblorrico",
    "Puente Nacional",
    "Puerres",
    "Puerto Asís",
    "Puerto Berrío",
    "Puerto Boyacá",
    "Puerto Caicedo",
    "Puerto Carreño",
    "Puerto Colombia",
    "Puerto Concordia",
    "Puerto Escondido",
    "Puerto Gaitán",
    "Puerto Guzmán",
    "Puerto Leguízamo",
    "Puerto Libertador",
    "Puerto Lleras",
    "Puerto López",
    "Puerto Nare",
    "Puerto Nariño",
    "Puerto Parra",
    "Puerto Rico",
    "Puerto Rondón",
    "Puerto Salgar",
    "Puerto Santander",
    "Puerto Tejada",
    "Puerto Triunfo",
    "Puerto Wilches",
    "Pulí",
    "Pupiales",
    "Puracé",
    "Purificación",
    "Purísima",
    "Pácora",
    "Páez",
    "Páramo",
    "Quebradanegra",
    "Quetame",
    "Quibdó",
    "Quimbaya",
    "Quinchía",
    "Quipile",
    "Quípama",
    "Ragonvalia",
    "Ramiriquí",
    "Recetor",
    "Regidor",
    "Remedios",
    "Remolino",
    "Repelón",
    "Restrepo",
    "Ricaurte",
    "Rioblanco",
    "Riofrío",
    "Riohacha",
    "Rionegro",
    "Riosucio",
    "Risaralda",
    "Rivera",
    "Roberto Payán",
    "Roldanillo",
    "Roncesvalles",
    "Rondón",
    "Rosas",
    "Rovira",
    "Ráquira",
    "Río Iró",
    "Río Quito",
    "Río Viejo",
    "Río de Oro",
    "Sabana de Torres",
    "Sabanagrande",
    "Sabanalarga",
    "Sabanas de San Ángel",
    "Sabaneta",
    "Saboyá",
    "Sahagún",
    "Saladoblanco",
    "Salamina",
    "Salazar de Las Palmas",
    "Saldaña",
    "Salento",
    "Salgar",
    "Samacá",
    "Samaniego",
    "Samaná",
    "Sampués",
    "San Agustín",
    "San Alberto",
    "San Andrés",
    "San Andrés de Cuerquia",
    "San Andrés de Sotavento",
    "San Antero",
    "San Antonio",
    "San Antonio de Palmito",
    "San Antonio del Tequendama",
    "San Benito",
    "San Benito Abad",
    "San Bernardo",
    "San Bernardo del Viento",
    "San Calixto",
    "San Carlos",
    "San Carlos de Guaroa",
    "San Cayetano",
    "San Cristóbal",
    "San Diego",
    "San Eduardo",
    "San Estanislao",
    "San Fernando",
    "San Francisco",
    "San Gil",
    "San Jacinto",
    "San Jacinto del Cauca",
    "San Jerónimo",
    "San Joaquín",
    "San José",
    "San José de Albán",
    "San José de Miranda",
    "San José de Pare",
    "San José de Uré",
    "San José de la Montaña",
    "San José del Fragua",
    "San José del Guaviare",
    "San José del Palmar",
    "San Juan Nepomuceno",
    "San Juan de Arama",
    "San Juan de Betulia",
    "San Juan de Rioseco",
    "San Juan de Urabá",
    "San Juan del Cesar",
    "San Juanito",
    "San Lorenzo",
    "San Luis",
    "San Luis de Gaceno",
    "San Luis de Palenque",
    "San Marcos",
    "San Martín",
    "San Martín de Loba",
    "San Mateo",
    "San Miguel",
    "San Miguel de Sema",
    "San Onofre",
    "San Pablo",
    "San Pablo de Borbur",
    "San Pedro",
    "San Pedro de Cartago",
    "San Pedro de Urabá",
    "San Pedro de los Milagros",
    "San Pelayo",
    "San Rafael",
    "San Roque",
    "San Sebastián",
    "San Sebastián de Buenavista",
    "San Vicente",
    "San Vicente de Chucurí",
    "San Vicente del Caguán",
    "San Zenón",
    "Sandoná",
    "Santa Ana",
    "Santa Bárbara",
    "Santa Bárbara de Pinto",
    "Santa Catalina",
    "Santa Fe de Antioquia",
    "Santa Helena del Opón",
    "Santa Isabel",
    "Santa Lucía",
    "Santa Marta",
    "Santa María",
    "Santa Rosa",
    "Santa Rosa de Cabal",
    "Santa Rosa de Osos",
    "Santa Rosa de Viterbo",
    "Santa Rosa del Sur",
    "Santa Rosalía",
    "Santa Sofía",
    "Santacruz",
    "Santana",
    "Santander de Quilichao",
    "Santiago",
    "Santo Domingo",
    "Santo Domingo de Silos",
    "Santo Tomás",
    "Santuario",
    "Sapuyes",
    "Saravena",
    "Sardinata",
    "Sasaima",
    "Sativanorte",
    "Sativasur",
    "Segovia",
    "Sesquilé",
    "Sevilla",
    "Siachoque",
    "Sibaté",
    "Sibundoy",
    "Silvania",
    "Silvia",
    "Simacota",
    "Simijaca",
    "Simití",
    "Sincelejo",
    "Sincé",
    "Sipí",
    "Sitionuevo",
    "Soacha",
    "Soatá",
    "Socha",
    "Socotá",
    "Sogamoso",
    "Solano",
    "Soledad",
    "Solita",
    "Somondoco",
    "Sonsón",
    "Sopetrán",
    "Soplaviento",
    "Sopó",
    "Sora",
    "Soracá",
    "Sotaquirá",
    "Sotará",
    "Suaita",
    "Suaza",
    "Subachoque",
    "Sucre",
    "Suesca",
    "Supatá",
    "Supía",
    "Suratá",
    "Susa",
    "Susacón",
    "Sutamarchán",
    "Sutatausa",
    "Sutatenza",
    "Suán",
    "Suárez",
    "Sácama",
    "Sáchica",
    "Tabio",
    "Tadó",
    "Talaigua Nuevo",
    "Tamalameque",
    "Tame",
    "Taminango",
    "Tangua",
    "Taraira",
    "Tarazá",
    "Tarqui",
    "Tarso",
    "Tasco",
    "Tauramena",
    "Tausa",
    "Tello",
    "Tena",
    "Tenerife",
    "Tenjo",
    "Tenza",
    "Teorama",
    "Teruel",
    "Tesalia",
    "Tibacuy",
    "Tibaná",
    "Tibasosa",
    "Tibirita",
    "Tibú",
    "Tierralta",
    "Timaná",
    "Timbiquí",
    "Timbío",
    "Tinjacá",
    "Tipacoque",
    "Tiquisio",
    "Titiribí",
    "Toca",
    "Tocaima",
    "Tocancipá",
    "Togüí",
    "Toledo",
    "Tolú",
    "Tolú Viejo",
    "Tona",
    "Topaipí",
    "Toribío",
    "Toro",
    "Tota",
    "Totoró",
    "Trinidad",
    "Trujillo",
    "Tubará",
    "Tuchín",
    "Tuluá",
    "Tumaco",
    "Tunja",
    "Tununguá",
    "Turbaco",
    "Turbaná",
    "Turbo",
    "Turmequé",
    "Tuta",
    "Tutazá",
    "Támara",
    "Támesis",
    "Tópaga",
    "Túquerres",
    "Ubalá",
    "Ubaque",
    "Ubaté",
    "Ulloa",
    "Une",
    "Unguía",
    "Unión Panamericana",
    "Uramita",
    "Uribia",
    "Urrao",
    "Urumita",
    "Usiacurí",
    "Valdivia",
    "Valencia",
    "Valle de San José",
    "Valle de San Juan",
    "Valle del Guamuez",
    "Valledupar",
    "Valparaíso",
    "Vegachí",
    "Venadillo",
    "Venecia",
    "Ventaquemada",
    "Vergara",
    "Versalles",
    "Vetas",
    "Vianí",
    "Victoria",
    "Vigía del Fuerte",
    "Vijes",
    "Villa Caro",
    "Villa Rica",
    "Villa de Leyva",
    "Villa del Rosario",
    "Villagarzón",
    "Villagómez",
    "Villahermosa",
    "Villamaría",
    "Villanueva",
    "Villapinzón",
    "Villarrica",
    "Villavicencio",
    "Villavieja",
    "Villeta",
    "Viotá",
    "Viracachá",
    "Vista Hermosa",
    "Viterbo",
    "Vélez",
    "Yacopí",
    "Yacuanquer",
    "Yaguará",
    "Yalí",
    "Yarumal",
    "Yolombó",
    "Yondó",
    "Yopal",
    "Yotoco",
    "Yumbo",
    "Zambrano",
    "Zapatoca",
    "Zapayán",
    "Zaragoza",
    "Zarzal",
    "Zetaquira",
    "Zipacón",
    "Zipaquirá",
    "Zona Bananera",
    "Ábrego",
    "Íquira",
    "Úmbita",
    "Útica",
]

# A handful of regional call-centre numbers (one per metro area) are reused
# by the source data as the "telefono" for every satellite town/branch
# served from that hub, rather than a number for the branch itself (e.g.
# small towns near Barranquilla all return Barranquilla's own number). These
# are not branch-specific so are excluded from the "phone" field.
SHARED_HOTLINE_NUMBERS = {
    "018000510510",
    "2359812",
    "2384447",
    "2762818",
    "2770413",
    "2868950",
    "3155039093",
    "3400363",
    "3581717",
    "4358282",
    "4850525",
    "5891019",
    "5943081",
    "6040525",
    "6064000",
    "6333535",
    "6849872",
    "6930153",
    "7282337",
    "7359393",
    "7897474",
    "8373200",
    "8630236",
    "8826903",
    "8837171",
    "8886808",
    "8918575",
}

TIME_RE = re.compile(r"(\d{1,2}):(\d{2})\s*([ap])\.?\s*m\.?", re.IGNORECASE)


def parse_time_range(text: str) -> tuple[str, str] | None:
    matches = TIME_RE.findall(text or "")
    if len(matches) != 2:
        return None

    def to_24h(hour: str, minute: str, meridiem: str) -> str:
        hour = int(hour)
        if meridiem.lower() == "p" and hour != 12:
            hour += 12
        elif meridiem.lower() == "a" and hour == 12:
            hour = 0
        return f"{hour:02d}:{minute}"

    (h1, m1, mer1), (h2, m2, mer2) = matches
    return to_24h(h1, m1, mer1), to_24h(h2, m2, mer2)


class OlimpicaCOSpider(Spider):
    name = "olimpica_co"
    item_attributes = {"brand": "Olímpica", "brand_wikidata": "Q24749847"}
    allowed_domains = ["www.olimpica.com"]

    # The store finder's VTEX Master Data resource only accepts an exact
    # "municipio" match in its "where" clause (no wildcards, "OR"/"AND"/"IN",
    # or unfiltered listing are accepted), so a request per municipality is
    # required. Querying via POST (rather than the persisted-query GET the
    # site itself uses) keeps the URL free of "&"/"%", which robots.txt
    # otherwise disallows for all query strings.
    graphql_query = """
        query GetDocuments($acronym: String, $fields: [String], $where: String)
          @context(sender: "olimpica.our-shops@0.0.5") {
          documents(acronym: $acronym, fields: $fields, where: $where, pageSize: 80)
            @context(provider: "vtex.store-graphql") {
            id
            fields {
              key
              value
            }
          }
        }
    """
    fields = [
        "municipio",
        "nombre",
        "direccion",
        "telefono",
        "lunesViernes",
        "horarioSabado",
        "horarioDomingo",
        "id",
    ]

    async def start(self) -> AsyncIterator[JsonRequest]:
        for municipio in MUNICIPIOS:
            yield JsonRequest(
                url="https://www.olimpica.com/_v/public/graphql/v1",
                data={
                    "query": self.graphql_query,
                    "variables": {"acronym": "NT", "fields": self.fields, "where": f'municipio="{municipio}"'},
                },
                cb_kwargs={"municipio": municipio},
            )

    def parse(self, response: Response, municipio: str, **kwargs: Any) -> Any:
        documents = (response.json().get("data") or {}).get("documents") or []
        for document in documents:
            store = {field["key"]: field["value"] for field in document["fields"] if field["value"] != "null"}
            # The API returns "municipio" in all caps; use the properly cased name queried with instead.
            store["city"] = municipio

            item = DictParser.parse(store)
            item["opening_hours"] = self.parse_opening_hours(store)
            if item.get("phone") in SHARED_HOTLINE_NUMBERS:
                item["phone"] = None

            apply_category(Categories.SHOP_SUPERMARKET, item)

            yield item

    def parse_opening_hours(self, store: dict) -> OpeningHours:
        oh = OpeningHours()
        if hours := parse_time_range(store.get("lunesViernes")):
            oh.add_days_range(DAYS_WEEKDAY, hours[0], hours[1])
        if hours := parse_time_range(store.get("horarioSabado")):
            oh.add_range(DAYS[5], hours[0], hours[1])
        if hours := parse_time_range(store.get("horarioDomingo")):
            oh.add_range(DAYS[6], hours[0], hours[1])
        return oh
