import scrapy
from scrapy.http import JsonRequest

from locations.dict_parser import DictParser


class RoadysUSSpider(scrapy.Spider):
    name = "roadys_us"
    item_attributes = {"brand": "Roady’s Truck Stops", "brand_wikidata": "Q7339701"}
    allowed_domains = ["roadys.com"]
    start_urls = ["https://api-v2.roadys.com/locations?show_all=true"]

    def start_requests(self):
        # Authorization Bearer is generated by packed static JavaScript and does not appear to change.
        headers = {
            "Authorization": "Bearer P7I6obDhgTejlPBV82F1W0cw1Qi7UeP9W40pS7d0xKB",
        }
        yield JsonRequest(url=self.start_urls[0], headers=headers)

    def parse(self, response):
        for location in response.json()["locations"]:
            item = DictParser.parse(location)
            item["ref"] = location["location_id"]
            item["name"] = location["location_name"]
            item["street_address"] = item.pop("addr_full")
            yield item
