name: Broken Spider
description: Report a specific issue with a spider
labels: bug
body:
  - type: input
    attributes:
      label: Spider name
      placeholder: example_gb
    validations:
      required: true
  - type: input
    attributes:
      label: Log output
      placeholder: https://www.alltheplaces.xyz/spiders/...
      description: >-
        If possible get the logs from [the latest](https://www.alltheplaces.xyz/spiders)
  - type: textarea
    attributes:
      label: Backtrace (if applicable)
  - type: textarea
    attributes:
      label: Example bad data or results
  - type: textarea
    attributes:
      label: Expected behaviour or results
