#!/usr/bin/env sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep ".py")

if ! [ -z "${FILES}" ]; then
    uv run autoflake8 --in-place $FILES
    uv run isort $FILES
    uv run black $FILES
    uv run python ci/check_spider_naming_consistency.py $FILES
fi
