#!/usr/bin/env sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep ".py")

if ! [ -z "${FILES}" ]; then
    pipenv run autoflake8 --in-place $FILES
    pipenv run isort $FILES
    pipenv run black $FILES
    pipenv run python ci/check_spider_naming_consistency.py $FILES
fi
