version: 0.2

env:
  variables:
    BUCKET: alltheplaces.openaddresses.io
    CODEBUILD_CACHE_BUCKET: codebuild-cache.openaddresses.io
  secrets-manager:
    ZYTE_API_KEY: "alltheplaces:ZYTE_API_KEY"
    GITHUB_APP_ID: "alltheplaces:GITHUB_APP_ID"
    GITHUB_APP_PRIVATE_KEY_BASE64: "alltheplaces:GITHUB_APP_PRIVATE_KEY_BASE64"
    GITHUB_APP_INSTALLATION_ID: "alltheplaces:GITHUB_APP_INSTALLATION_ID"

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - uv sync --cache-dir /root/.cache/uv
  build:
    commands:
      - uv run scrapy check
      - /bin/bash ci/run_pr_spiders.sh
  post_build:
    commands:
      - uv cache prune --ci

cache:
  paths:
    - /root/.cache/uv
