name: Sync Branch from Upstream Master
on:
  schedule:
    - cron: '0 0 * * 6'  # Runs at 00:00 UTC every Saturday
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/alltheplaces/alltheplaces.git
          git fetch upstream

      - name: Sync with upstream master
        run: |
          # Ensure we're on the master branch
          git checkout master
          
          # Merge upstream master into local master, with precedence to upstream
          git merge upstream/master -X theirs --allow-unrelated-histories
          
          # Stage all changes
          git add .

          # Commit the merge
          git commit -m "Sync with upstream master" || echo "No changes to commit"

          # Push the changes to the origin master branch
          git push origin master
        shell: /usr/bin/bash -e {0}

      - name: Check for conflicts
        run: |
          if git status | grep -q "You have unmerged paths"; then
            echo "::warning::There are merge conflicts. Please resolve them manually."
            exit 1
          fi

      - name: Trigger Deploy Production workflow
        if: success() && !contains(github.event.head_commit.message, 'skip ci')
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          event-type: deploy-production
